apiVersion: apps/v1
kind: Deployment
metadata:
  name: iistemplate2y
  
  labels:
    app: iistemplate2
spec:
  replicas: 1
  template:
    metadata:
      name: iistemplate2
      labels:
        app: iistemplate2
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: iistemplate2
        image: aspacr.azurecr.io/temp/iis
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: iistemplate2
---
apiVersion: v1
kind: Service
metadata:
  name: iistemplate2
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: iistemplate2